### ISSUE TITLE
KeyError: 'SampleTimeFine'

### ISSUE THREAD

**Issue by Jebediah** [xsens/xsens_mti_ros_node#13]
Node is crashing consistently after starting. Using a MTi-G-710-2A5G4.

`
[WARN] [WallTime: 1469577089.593448] Cannot find value for parameter: ~device, assigning default: auto`
`
[WARN] [WallTime: 1469577089.594456] Cannot find value for parameter: ~baudrate, assigning default: 0`
`
Timeout defaults to 0.020s based on output settings.
`
`
[INFO] [WallTime: 1469577090.848241] Detected MT device on port /dev/ttyUSB0 @ 115200 bps
`
`
[INFO] [WallTime: 1469577090.848563] MT node interface: /dev/ttyUSB0 at 115200 bd.
`
`
Timeout defaults to 0.020s based on output settings.
`
`
[INFO] [WallTime: 1469577091.170101] Found parameter: ~frame_id, value: /imu
`
`
[INFO] [WallTime: 1469577091.171322] Found parameter: ~frame_local, value: ENU
`
`
[INFO] [WallTime: 1469577091.172411] Found parameter: ~frame_local_imu, value: ENU
`
`
Traceback (most recent call last):
`
`
  File "/home/dev/catkin_ws/src/xsens_driver/src/mtnode.py", line 373, in <module>
`
`
    main()
`
`
  File "/home/dev/catkin_ws/src/xsens_driver/src/mtnode.py", line 369, in main
`
`
    driver.spin()
`
`
  File "/home/dev/catkin_ws/src/xsens_driver/src/mtnode.py", line 112, in spin
`
`
    self.spin_once()
`
`
  File "/home/dev/catkin_ws/src/xsens_driver/src/mtnode.py", line 184, in spin_once
`
`
    time = time_data['SampleTimeFine']
`
`
KeyError: 'SampleTimeFine'
`

**Comment by Jebediah** [comment]
Needed to run mtdevice.py first.
