### ISSUE TITLE
mode 3 and 1 of xsens mti 10 error

### ISSUE THREAD

**Issue by bilelxlab** [xsens/xsens_mti_ros_node#19]
hello 
i followed your Readme and i succeeded to make it work only in mode -m 2 
i am interested in getting the orientation but i have the following error when using : 

rosrun xsens_driver mtdevice.py -m 3  -f 50
rosrun xsens_driver mtnode.py _device:=/dev/ttyUSB0 _baudrate:=115200

[INFO] [WallTime: 1487110827.120157] Found parameter: ~device, value: /dev/ttyUSB0
[INFO] [WallTime: 1487110827.121863] Found parameter: ~baudrate, value: 115200
[INFO] [WallTime: 1487110827.122180] MT node interface: /dev/ttyUSB0 at 115200 bd.
Timeout defaults to 0.026s based on output settings.
[WARN] [WallTime: 1487110827.444168] Cannot find value for parameter: ~frame_id, assigning default: /mti/data
[WARN] [WallTime: 1487110827.448107] Cannot find value for parameter: ~frame_local, assigning default: ENU
[WARN] [WallTime: 1487110827.451878] Cannot find value for parameter: ~frame_local_imu, assigning default: ENU
Traceback (most recent call last):
  File "/home/toshiba/catkin_ws/src/xsens_driver/nodes/mtnode.py", line 373, in <module> main()
  File "/home/toshiba/catkin_ws/src/xsens_driver/nodes/mtnode.py", line 369, in main driver.spin()
  File "/home/toshiba/catkin_ws/src/xsens_driver/nodes/mtnode.py", line 112, in spin self.spin_once()
  File "/home/toshiba/catkin_ws/src/xsens_driver/nodes/mtnode.py", line 129, in spin_once data = self.mt.read_measurement()
File "/home/toshiba/catkin_ws/src/xsens_driver/nodes/mtdevice.py", line 520, in read_measurement mid, data = self.read_msg()
File "/home/toshiba/catkin_ws/src/xsens_driver/nodes/mtdevice.py", line 140, in read_msg raise MTException("timeout waiting for message.")
mtdef.MTException: MT error: timeout waiting for message.

I am using Ubuntu 14.04
can you help me ?

**Comment by arunvydhya** [comment]
hello, 
Could you let us know what kind of MTi device you are using? It could be that you have a MTi-1/10/100 device which does not support orientation output.
