### ISSUE TITLE
Time out issue, cannot connect to Device.

### ISSUE THREAD

**Issue by MomoTavas** [xsens/xsens_mti_ros_node#23]
Hi,

I have tried to run the node but I was not successful. Here is the log. While I could just use the sensor under normal (none-ROS)executable file and see the output.
Could it have done anything with the baudrate?

$ rosrun xsens_driver mtdevice.py -m 1 -f 100
MT error: timeout waiting for message.

momo@Momo-Lenovo:~/catkin_ws$ rosrun xsens_driver mtnode.py _device:=/dev/ttyUSB0 _baudrate:=115200
[INFO] [1504479547.096812]: Found parameter: ~device, value: /dev/ttyUSB0
[INFO] [1504479547.103987]: Found parameter: ~baudrate, value: 115200
[INFO] [1504479547.105051]: MT node interface: /dev/ttyUSB0 at 115200 bd.
Traceback (most recent call last):
  File "/home/momo/catkin_ws/src/xsens_driver/src/mtnode.py", line 373, in <module>
    main()
  File "/home/momo/catkin_ws/src/xsens_driver/src/mtnode.py", line 368, in main
    driver = XSensDriver()
  File "/home/momo/catkin_ws/src/xsens_driver/src/mtnode.py", line 61, in __init__
    self.mt = mtdevice.MTDevice(device, baudrate)
  File "/home/momo/catkin_ws/src/xsens_driver/src/mtdevice.py", line 29, in __init__
    self.auto_config()
  File "/home/momo/catkin_ws/src/xsens_driver/src/mtdevice.py", line 535, in auto_config
    self.GoToConfig()
  File "/home/momo/catkin_ws/src/xsens_driver/src/mtdevice.py", line 209, in GoToConfig
    self.write_ack(MID.GoToConfig)
  File "/home/momo/catkin_ws/src/xsens_driver/src/mtdevice.py", line 182, in write_ack
    mid_ack, data_ack = self.read_msg()
  File "/home/momo/catkin_ws/src/xsens_driver/src/mtdevice.py", line 140, in read_msg
    raise MTException("timeout waiting for message.")
mtdef.MTException: MT error: timeout waiting for message.

Thanks.

**Comment by arunvydhya** [comment]
This is quite similar to the issue we have addressed before - please follow the steps suggested in https://github.com/xsens/xsens_mti_ros_node/issues/8
