### ISSUE TITLE
Errors on launching the ROS package

### ISSUE THREAD

**Issue by zongyaojin** [xsens/xsens_mti_ros_node#34]
Hello,

I have an MTi-G-710 sensor, and it's connected to a Ubuntu 16.04 computer with ROS Kinetic.

When I launch the package, it shows the following errors:

```
~/ws/research/ros$ roslaunch xsens_driver xsens.launch 
... logging to /home/zongyao/.ros/log/f11847dc-9507-11e8-a682-34f39af35331/roslaunch-x1-7901.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.31.100:46065/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /xsens_mti/baudrate: 115200
 * /xsens_mti/configure_on_startup: True
 * /xsens_mti/device: /dev/ttyUSB0
 * /xsens_mti/frame_id: xsens
 * /xsens_mti/odr: 400
 * /xsens_mti/output_mode: 3
 * /xsens_mti/use_rostime: True
 * /xsens_mti/xkf_scenario: 1

NODES
  /
    xsens_mti (xsens_driver/mtnode.py)

auto-starting new master
process[master]: started with pid [7911]
ROS_MASTER_URI=http://192.168.31.100:11311

setting /run_id to f11847dc-9507-11e8-a682-34f39af35331
process[rosout-1]: started with pid [7924]
started core service [/rosout]
process[xsens_mti-2]: started with pid [7934]
[WARN] [1533072200.350604]: timeout waiting for message
Traceback (most recent call last):
  File "/home/zongyao/ws/research/ros/src/xsens_driver/src/mtnode.py", line 392, in <module>
    main()
  File "/home/zongyao/ws/research/ros/src/xsens_driver/src/mtnode.py", line 387, in main
    driver = XSensDriver()
  File "/home/zongyao/ws/research/ros/src/xsens_driver/src/mtnode.py", line 77, in __init__
    self.mt.SetCurrentScenario(xkf_scenario)
  File "/home/zongyao/ws/research/ros/src/xsens_driver/src/mtdevice.py", line 373, in SetCurrentScenario
    self.write_ack(MID.SetCurrentScenario, (0x00, scenario_id&0xFF))
  File "/home/zongyao/ws/research/ros/src/xsens_driver/src/mtdevice.py", line 182, in write_ack
    mid_ack, data_ack = self.read_msg()
  File "/home/zongyao/ws/research/ros/src/xsens_driver/src/mtdevice.py", line 141, in read_msg
    if ord(c)<>0xFA:
TypeError: ord() expected a character, but string of length 0 found
[xsens_mti-2] process has died [pid 7934, exit code 1, cmd /home/zongyao/ws/research/ros/src/xsens_driver/src/mtnode.py __name:=xsens_mti __log:=/home/zongyao/.ros/log/f11847dc-9507-11e8-a682-34f39af35331/xsens_mti-2.log].
log file: /home/zongyao/.ros/log/f11847dc-9507-11e8-a682-34f39af35331/xsens_mti-2*.log
^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

And my group setting is as follows:

```
~$ ls -l /dev/ttyUSB0 

crw-rw---- 1 root plugdev 188, 0 Jul 31 16:23 /dev/ttyUSB0

~$ groups

dialout adm lp cdrom sudo dip plugdev lpadmin sambashare libvirtd docker zongyao
```

I was wondering if someone could help me out?

**Comment by zongyaojin** [comment]
Never mind, it seems working now, editing group solves the problem.
