### ISSUE TITLE
KeyError: 'SampleTimeFine'

### ISSUE THREAD

**Issue by wujiang** [xsens/xsens_mti_ros_node#46]
Device: MTi-30
Firmware: 1.7.2

Error:

```
Traceback (most recent call last):
  File "/home/nvidia/labs-scv/src/xsens_driver/src/mtnode.py", line 400, in <module>
    main()
  File "/home/nvidia/labs-scv/src/xsens_driver/src/mtnode.py", line 396, in main
    driver.spin()
  File "/home/nvidia/labs-scv/src/xsens_driver/src/mtnode.py", line 131, in spin
    self.spin_once()
  File "/home/nvidia/labs-scv/src/xsens_driver/src/mtnode.py", line 211, in spin_once
    time = time_data['SampleTimeFine']
KeyError: 'SampleTimeFine'
```

Inspected `data`, got this
```
{'Status': {'StatusWord': 3}, 'Timestamp': {'PacketCounter': 23041}, 'Orientation Data': {'Q1': -0.0018019694834947586, 'Q0': 0.1061224490404129, 'Q3': -0.9943498969078064, 'Q2': -0.001756915939040482}}
```

**Comment by wujiang** [comment]
I had to uncheck and check `Sample Time Fine` in MT manager's output config window to get rid of this error.
